services:
  - type: web
    name: todo-backend
    runtime: java
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    healthCheckPath: /api/test
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_VERSION
        value: 17
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: todo-database
          property: internalConnectionString

databases:
  - name: todo-database
    databaseName: todo
    user: todo_user
    plan: free
    region: oregon
